on: [push, pull_request]
name: Python Tests
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x]
        python-version: [3.8] #3.6, 3.7,
        platform: [windows-latest] #ubuntu-latest, macos-latest,
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install CFFI built by MinGW
      if: runner.os == 'Windows'
      run: |
        bash -c "pacman --noconfirm -S mingw-w64-i686-python-cffi"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install -r python/requirements.dev.txt
    - name: Build and install package
      run: |
        pip install -e python
    - name: Test
      run: |
        pytest python/
